### ISSUE TITLE
[Feature Request] Disable Two-Step Hotkey Feature

### ISSUE THREAD

**Issue by ItsukaHiro** [NotRyken/QuickMessages#1]
I want a way to using JUST ONE key to instant send message or command. It will much more convenient in some cases.
Also, an option to disable display command in actionbar
Bonus: I'm ok with dependence, like cloth-config.

**Comment by NotRyken** [comment]
It is true that a single-step hotkey would be more convenient in some cases, but there is a good reason that this mod uses a two-step system. My keyboard has ~74 bindable keys, and 67 of those are already bound to other functions. I also currently have 21 quick messages loaded. So, if I were to implement a single-step hotkey, I would have to lose 14 functions/messages.

Disabling the command display is doable, though I'm curious to know why you want it?

**Comment by ItsukaHiro** [comment]
Actually, I think the mod shuold have an OPTION, mean if player think two-step hotkey is not nessessory, they can freely disable them.

About actionbar, most of message or command have the own response in the chat, mean you can still know actual message or command you just sent. And disable that can make the play-flow more consistent. And once again it's just an option and can be enable/disable in the setting.

**Comment by NotRyken** [comment]
A quick search reveals that are multiple alternative mods implementing a single-hotkey approach. Perhaps not yet on the latest MC version, but you can get in touch with their developers about updating.

Your suggestion is considered, but I will not give an ETA for a final decision or change at this time.
