### ISSUE TITLE
Re-allow empty and/or whitespace only macros

### ISSUE THREAD

**Issue by Starjon** [NotRyken/QuickMessages#14]
### Mod Version

2.3.4+1.21.4

### Mod Loader

Fabric

### Minecraft Version

1.21.4

### Bug Description

Since some recent version the mod no longer allows emtpty or whitespace only macros (e.g. " "). This was possible with some earlier version, and useful for me to de facto add a second button which opens the chat (in addition to the usual keybind).

### Expected Behavior

An empty, or a whitespace only command, should not be allowed, at least for display only macros.

### Reproduction Steps

Create a macro with empty or whitespace only command, close the menu and reopen it. The macro has disappeared. The same happens if the macro is entered into the configuration file manually.

### Log File

none

**Comment by NotRyken** [comment]
Empty messages and macros are automatically cleaned up on config save. 

If you want to send a message then open chat with a single keypress, you can bind the macro to your chat key and set it to `assert` mode.

If you are only using the macro to have two ways of opening chat, that's out of scope for this mod.

If you aren't doing either of those things, please elaborate on exactly what you want to be able to do, and why.

**Comment by Starjon** [comment]
Using the macro to have two ways of opening chat is one use-case of this, but not the only one. Another macro I have, which used to work, issues two commands and then opens the chat afterwards (basically for teleporting me to my afk position, setting me as afk and the opening the chat so that I don't move (which would set me as non-afk again)). If this is out of scope of this mod, that's your call to make (though unfortunate for me). I assumed it to be unintentional because it used to work with a recent version.

**Comment by NotRyken** [comment]
Seems reasonable.
