### ISSUE TITLE
Optional delay between commands bound to a single key

### ISSUE THREAD

**Issue by Stromsaaas** [NotRyken/QuickMessages#2]
It would be pretty handy if it would be possible to set a delay between commands when a chain of commands is bound to one key. The current problem is that some commands take time to execute and other commands might depend on the result of the first command.

Also, some servers kick you or throw exceptions when executing commands to fast.

**Comment by NotRyken** [comment]
Thanks for the suggestion. Due to requiring gui and config changes this will be on hold for approx two or three weeks until I have time to address it.

**Comment by NotRyken** [comment]
Added in v2.0.0
