### ISSUE TITLE
Mix "Send" and "Type" options within macro

### ISSUE THREAD

**Issue by Starjon** [NotRyken/QuickMessages#3]
### Request Description

Could you make it possible to type and send commands in the same macro? Or, as a workaround, could you run all macros that correspond to a keybind, not just the first? (That would allow to have one macro send the commands and another type what you want to type). Would appreciate that. :)

**Comment by NotRyken** [comment]
I think the latter is probably feasible, I have to look at overhauling the GUI as well though so it'll take some time.

**Comment by NotRyken** [comment]
Experimental release 2.1.0-beta.1 is out with support for multiple-activation, let me know if you encounter any issues.
