### ISSUE TITLE
[NeoForge 1.21.1] Crash on Clicking Mod Config Button in Mods Menu

### ISSUE THREAD

**Issue by jmdev91** [NotRyken/QuickMessages#6]
### Mod Version

v2.0.0, v2.1.0-beta.1, v2.1.0-beta.2

### Mod Loader

NeoForge (v21.1.55 and v21.1.53)

### Minecraft Version

1.21.1

### Bug Description

As soon as the Config button is clicked in NeoForge's mod menu, the game crashes to desktop. This happens from the main menu, after loading into single-player worlds and after loading into multiplayer servers. Once in-game, the menu can be brought up using its keybind without issue.

### Expected Behavior

The menu brought up when in-game using the keybind should appear, if I understand the mod page correctly.

### Reproduction Steps

Install mod
Open Mods list at Main Menu or in the Pause Menu while playing
Click CommandKeys, then Config.
Observe crash

### Log File

[latest.log](https://github.com/user-attachments/files/17050059/latest.log)

### Crash Report (optional)

[crash-2024-09-18_16.26.48-client.txt](https://github.com/user-attachments/files/17050067/crash-2024-09-18_16.26.48-client.txt)

**Comment by NotRyken** [comment]
Confirmed, thanks for reporting. This currently affects all configurable TMC mods. I've updated the compatible MC version indexes, removing NeoForge 1.21.1 for the moment. Unfortunately no ETA on a fix - this is a priority I'm just very short on time right now.

**Comment by jmdev91** [comment]
No worries, in my case I was looking for something to use on servers and moved loaders to use something a little less risky (accidental repeat could be disastrous) and GUI based. The profile features of this look really cool, though.
