### ISSUE TITLE
[Feature Request] Add Clipboard Auto-Input in Hotkey

### ISSUE THREAD

**Issue by Lucanoria** [NotRyken/QuickMessages#7]
### Request Description

I don't know how many users would use this, but I personally would like to have the clipboard automatically input with a custom hotkey. For example, if you have a hotkey like this: '/commandXYZ [cp]', it would save a Ctrl+V.

[cp] would then be replaced by the current clipboard

### Minecraft Version

1.20.1 would be very awesome

**Comment by Lucanoria** [comment]
The benefit of this would be for 'Build the Earth 1:1'. In this project, you constantly have to measure building edges and corners using "//tpll [coords]", which you copy from Google Maps or Earth. Thanks to the hotkey, you already save most keystrokes, but if you could automatically paste and enter from the clipboard, it would be optimal.

**Comment by NotRyken** [comment]
Thanks for the suggestion. As of `v2.2.0-beta.01`, the clipboard can be accessed using the `%clipboard%` placeholder.
Please verify that it works as expected since I've had limited time to test it, particularly on 1.20.1.

**Comment by Lucanoria** [comment]
It works as Intended, thank you very much for the backport <3
